### ISSUE TITLE
Hubitat Xbar exit status 99

### ISSUE THREAD

**Issue by hayes1699** [KurtSanders/Hubitat-Xbar#1]
Have everything installed, getting error "exit status 99". Run in terminal and get this. any suggestions? 

mac ventura 13.2.1
python 3.10

Last login: Thu Feb 23 15:02:23 on ttys000
VAR_verbose_schedule_notify="XXXXXX" '/Users/jh/Library/Application Support/xbar/plugins/Hubitat_XBar.5m.py'
jh@Jonathans-MBP ~ % VAR_verbose_schedule_notify="true" VAR_verbose_request_notify="true" VAR_Hubitat_Oauth_String="XXXXXX" '/Users/jh/Library/Application Support/xbar/plugins/Hubitat_XBar.5m.py'
:rage:
---
:thumbsdown: HTTPS Error Encountered: Communicating to Hub API caused the following error: HTTP Error 500: Server Error
==> Please check your Internet Connectivity and Refresh Xbar again when Online
jh@Jonathans-MBP ~ %

**Comment by KurtSanders** [comment]
Did you enter your API string that was generated from the Hubitat → Xbar app?  The VAR_Hubitat_Oauth_String should not be XXXX (unless you have masked it).  Also, can you look at the Hubitat Log View and see if there is any specific errors being generated by the Hubitat → Xbar Plugin app when you refresh Xbar.  If you want we can try to diagnose via a phone call.  If that is an avenue you want to try, email me at kurt@kurtsanders.com with your phone number and we can start a text message thread to see when it is convenient.  I am in EST timezone.

**Comment by KurtSanders** [comment]
No response, closing issue
