### ISSUE TITLE
exit status 244

### ISSUE THREAD

**Issue by cmhaagen** [KurtSanders/Hubitat-Xbar#2]
I installed xbar 2.1.7-beta and Hubitat_XBar.5m.py, following the instructions at [https://github.com/KurtSanders/Hubitat-Xbar/blob/main/README.md](https://github.com/KurtSanders/Hubitat-Xbar/blob/main/README.md). I configured xBar using the Oauth API string from the Hubitat -> xBar Plugin. The local test link works fine, but xBar just shows an error "exit status 244". I'm not sure, but I think this might correspond to an HTTP 500 error?  Any ideas what is wrong?

**Comment by KurtSanders** [comment]
Can you check the Hubitat logs for an error message when you refresh the Xbar plugin.  I'm thinking that the app is not configured correctly and we might be able to see the error on the Hubitat logs.  

If not we can try to connect via Facetime next week when we are free to troubleshoot the error?  My email is kurt@kurtsanders.com

**Comment by cmhaagen** [comment]
Nothing in the logs. But when I use the xBar command "Run in Terminal", I
get the following error:

:thumbsdown: HTTPS Error Encountered: Communicating to Hub API caused the
following error: HTTP Error 404: Not Found
==> Please check your Internet Connectivity and Refresh Xbar again when
Online

Of course, there are no issues with my network connection.

Cheers,
*-Chris*

**Comment by cmhaagen** [comment]
I resolved the issue. In v1.0.3 of the xBar plugin, the Set URLs (lines 292-301) include a forward slash '/' at the end of the path, before the query string separator '?'. I removed the forward slash. Now everything works fine. :)

**Comment by KurtSanders** [comment]
The 404 is a RC status code that the requested page is not available, most likely the http request to your hubitat server.  

- Verify your Xbar Plugin API string is configured exactly as it is displayed in the Hubitat → XBar Plugin app? It is the one that has the tilde ~ character ie =>  **11111xxx11-b1b1-1111-c54r-sdn12j3h4~http://10.0.0.2/apps/api/1111/** 
- Try the generated http testing strings on the bottom of the API OAuth Setup screen work in your browser when you click them from the Hubitat → XBar Plugin app API Oauth page?

**Comment by KurtSanders** [comment]
Wow, good catch and debugging!  

That is definitely a weird issue since v1.03 works on mine and several others that are using.  However, a ending '/' before the '?" is not URL correct, so I will update the app and python to v1.04 version to remove that extra /.

Again, great work!
